"""add_source_job_id_to_raw_jobs

Revision ID: 0911c420e154
Revises: 9156adb38e4f
Create Date: 2026-07-02 03:01:27.350982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0911c420e154'
down_revision: Union[str, Sequence[str], None] = '9156adb38e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_jobs', sa.Column('source_job_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_raw_jobs_source_job_id'), 'raw_jobs', ['source_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_jobs_source_job_id'), table_name='raw_jobs')
    op.drop_column('raw_jobs', 'source_job_id')
    # ### end Alembic commands ###
