"""create_raw_jobs

Revision ID: 9156adb38e4f
Revises: 0cce4b724d8b
Create Date: 2026-07-02 02:41:38.011305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9156adb38e4f'
down_revision: Union[str, Sequence[str], None] = '0cce4b724d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('company_logo', sa.String(length=512), nullable=True),
    sa.Column('company_website', sa.String(length=512), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_jobs_id'), 'raw_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_raw_jobs_source'), 'raw_jobs', ['source'], unique=False)
    op.create_index(op.f('ix_raw_jobs_status'), 'raw_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_raw_jobs_url'), 'raw_jobs', ['url'], unique=True)
    op.add_column('resume_parsed_data', sa.Column('quality_score_reason', sa.Text(), nullable=True))
    op.add_column('resume_parsed_data', sa.Column('ats_score_reason', sa.Text(), nullable=True))
    op.add_column('resume_parsed_data', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('resume_parsed_data', sa.Column('embedding_dimensions', sa.Integer(), nullable=True))
    op.alter_column('resume_parsed_data', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('resume_parsed_data', 'ats_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('resume_versions', sa.Column('ocr_status', sa.String(length=20), server_default='READY', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_versions', 'ocr_status')
    op.alter_column('resume_parsed_data', 'ats_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('resume_parsed_data', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('resume_parsed_data', 'embedding_dimensions')
    op.drop_column('resume_parsed_data', 'embedding_model')
    op.drop_column('resume_parsed_data', 'ats_score_reason')
    op.drop_column('resume_parsed_data', 'quality_score_reason')
    op.drop_index(op.f('ix_raw_jobs_url'), table_name='raw_jobs')
    op.drop_index(op.f('ix_raw_jobs_status'), table_name='raw_jobs')
    op.drop_index(op.f('ix_raw_jobs_source'), table_name='raw_jobs')
    op.drop_index(op.f('ix_raw_jobs_id'), table_name='raw_jobs')
    op.drop_table('raw_jobs')
    # ### end Alembic commands ###
