"""add_job_category

Revision ID: b07b5ad464fe
Revises: 26fb44216e4f
Create Date: 2026-07-09 11:55:43.190237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07b5ad464fe'
down_revision: Union[str, Sequence[str], None] = '26fb44216e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_category', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('category_confidence', sa.Float(), nullable=True))
    op.create_index(op.f('ix_jobs_job_category'), 'jobs', ['job_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_category'), table_name='jobs')
    op.drop_column('jobs', 'category_confidence')
    op.drop_column('jobs', 'job_category')
    # ### end Alembic commands ###
