"""sprint2_normalization_deduplication

Revision ID: be0fc3a9f472
Revises: 0911c420e154
Create Date: 2026-07-06 21:11:44.483384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0fc3a9f472'
down_revision: Union[str, Sequence[str], None] = '0911c420e154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('skill_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_aliases_alias'), 'skill_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_skill_aliases_id'), 'skill_aliases', ['id'], unique=False)
    op.add_column('job_skills', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_skills', 'skills', ['skill_id'], ['id'], ondelete='SET NULL')
    op.add_column('jobs', sa.Column('original_company_name', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('normalized_company_name', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('remote_type', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('salary_period', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('duplicate_group_id', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('duplicate_reason', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('duplicate_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_jobs_city'), 'jobs', ['city'], unique=False)
    op.create_index(op.f('ix_jobs_country'), 'jobs', ['country'], unique=False)
    op.create_index(op.f('ix_jobs_duplicate_group_id'), 'jobs', ['duplicate_group_id'], unique=False)
    op.create_index(op.f('ix_jobs_embedding_status'), 'jobs', ['embedding_status'], unique=False)
    op.create_index(op.f('ix_jobs_employment_type'), 'jobs', ['employment_type'], unique=False)
    op.add_column('resume_skills', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resume_skills', 'skills', ['skill_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_skills', type_='foreignkey')
    op.drop_column('resume_skills', 'skill_id')
    op.drop_index(op.f('ix_jobs_employment_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_embedding_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_duplicate_group_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_country'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_city'), table_name='jobs')
    op.drop_column('jobs', 'duplicate_score')
    op.drop_column('jobs', 'duplicate_reason')
    op.drop_column('jobs', 'duplicate_group_id')
    op.drop_column('jobs', 'salary_period')
    op.drop_column('jobs', 'remote_type')
    op.drop_column('jobs', 'country')
    op.drop_column('jobs', 'state')
    op.drop_column('jobs', 'city')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'normalized_company_name')
    op.drop_column('jobs', 'original_company_name')
    op.drop_constraint(None, 'job_skills', type_='foreignkey')
    op.drop_column('job_skills', 'skill_id')
    op.drop_index(op.f('ix_skill_aliases_id'), table_name='skill_aliases')
    op.drop_index(op.f('ix_skill_aliases_alias'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
