DEV_SAMPLE_JOBS = [
    {
        "title": "Senior React Developer",
        "company_name": "Vercel",
        "description": "Looking for a seasoned frontend engineer to help craft the future of Next.js and frontend dev. Experience with React, TypeScript, and server components is required.",
        "location": "San Francisco, CA",
        "job_type": "Full-time",
        "is_remote": True,
        "url": "https://vercel.com/careers/sr-react-dev",
        "company_logo": "https://vercel.com/favicon.ico",
        "skills": ["React", "TypeScript", "Next.js", "TailwindCSS"],
        "salary_min": 140000,
        "salary_max": 180000,
        "is_seed_data": True,
        "data_origin": "SEED"
    },
    {
        "title": "Python AI Engineer",
        "company_name": "OpenAI",
        "description": "Work on training and fine-tuning large language models. Strong Python foundation, experience with PyTorch, Transformers, and vector databases required.",
        "location": "San Francisco, CA",
        "job_type": "Full-time",
        "is_remote": False,
        "url": "https://openai.com/careers/python-ai-engineer",
        "company_logo": "https://openai.com/favicon.ico",
        "skills": ["Python", "PyTorch", "Transformers", "AI", "Vector DB"],
        "salary_min": 180000,
        "salary_max": 250000,
        "is_seed_data": True,
        "data_origin": "SEED"
    },
    {
        "title": "Full Stack Software Engineer",
        "company_name": "Supabase",
        "description": "Help us build the open-source Firebase alternative. Experience with Go, TypeScript, PostgreSQL, and database design is key.",
        "location": "Singapore",
        "job_type": "Full-time",
        "is_remote": True,
        "url": "https://supabase.com/careers/full-stack-engineer",
        "company_logo": "https://supabase.com/favicon.ico",
        "skills": ["TypeScript", "PostgreSQL", "Go", "Supabase", "React"],
        "salary_min": 110000,
        "salary_max": 150000,
        "is_seed_data": True,
        "data_origin": "SEED"
    },
    {
        "title": "DevOps Architect",
        "company_name": "HashiCorp",
        "description": "Manage multi-cloud infrastructure deployment scripts. Focus on Terraform, Kubernetes, Consul, and Docker security compliance.",
        "location": "Seattle, WA",
        "job_type": "Full-time",
        "is_remote": True,
        "url": "https://hashicorp.com/careers/devops-architect",
        "company_logo": "https://hashicorp.com/favicon.ico",
        "skills": ["Terraform", "Kubernetes", "AWS", "Docker", "DevOps"],
        "salary_min": 130000,
        "salary_max": 170000,
        "is_seed_data": True,
        "data_origin": "SEED"
    },
    {
        "title": "Senior Software Engineer - Backend",
        "company_name": "Flipkart",
        "description": "Join the Flipkart Core Marketplace engineering team. You will build highly scalable distributed microservices handling millions of requests per minute. Experience with Java, Spring Boot, MySQL, and Kafka is required.",
        "location": "Bengaluru, Karnataka, India",
        "job_type": "Full-time",
        "is_remote": False,
        "url": "https://careers.flipkart.com/jobs/senior-software-engineer-backend-blr",
        "company_logo": "https://images.livemint.com/img/2021/04/16/600x338/flipkart-kH3F--621x349@LiveMint_1618567119293.jpg",
        "skills": ["Java", "Spring Boot", "MySQL", "Kafka", "Distributed Systems"],
        "salary_min": 2400000,
        "salary_max": 3500000,
        "currency": "INR",
        "is_seed_data": True,
        "data_origin": "SEED"
    },
    {
        "title": "Full Stack Developer",
        "company_name": "Zomato",
        "description": "Looking for a Full Stack Developer to build features for Zomato Gold and merchant dashboards. Experience with React, Node.js, and PostgreSQL is required. Knowledge of React Native is a plus.",
        "location": "Gurugram, Haryana, India",
        "job_type": "Full-time",
        "is_remote": False,
        "url": "https://careers.zomato.com/jobs/full-stack-developer-ggn",
        "company_logo": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Zomato_Logo.svg",
        "skills": ["React", "Node.js", "PostgreSQL", "JavaScript", "TypeScript"],
        "salary_min": 1800000,
        "salary_max": 2800000,
        "currency": "INR",
        "is_seed_data": True,
        "data_origin": "SEED"
    },
    {
        "title": "Senior Frontend Engineer",
        "company_name": "Razorpay",
        "description": "Help Razorpay redefine online payment experiences for millions of merchants. You will build fast, secure, and beautiful dashboard interfaces using React, Next.js, TailwindCSS, and TypeScript.",
        "location": "Bengaluru, Karnataka, India",
        "job_type": "Full-time",
        "is_remote": True,
        "url": "https://razorpay.com/jobs/senior-frontend-engineer-blr",
        "company_logo": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Razorpay_logo.svg",
        "skills": ["React", "Next.js", "TailwindCSS", "TypeScript", "Redux"],
        "salary_min": 2000000,
        "salary_max": 3200000,
        "currency": "INR",
        "is_seed_data": True,
        "data_origin": "SEED"
    },
    {
        "title": "Data Engineer",
        "company_name": "Paytm",
        "description": "Design, build and maintain robust data pipelines handling transactions data. Experience with Python, Spark, Hadoop, Hive, and AWS Redshift is key.",
        "location": "Noida, Uttar Pradesh, India",
        "job_type": "Full-time",
        "is_remote": False,
        "url": "https://careers.paytm.com/jobs/data-engineer-noida",
        "company_logo": "https://upload.wikimedia.org/wikipedia/commons/2/24/Paytm_Logo.svg",
        "skills": ["Python", "Apache Spark", "Hadoop", "AWS Redshift", "SQL"],
        "salary_min": 1500000,
        "salary_max": 2500000,
        "currency": "INR",
        "is_seed_data": True,
        "data_origin": "SEED"
    },
    {
        "title": "Backend Software Engineer",
        "company_name": "Swiggy",
        "description": "Build high-throughput and low-latency systems for order placement and delivery assignment. Experience with Go, Redis, Kafka, and PostgreSQL is required.",
        "location": "Bengaluru, Karnataka, India",
        "job_type": "Full-time",
        "is_remote": False,
        "url": "https://careers.swiggy.com/jobs/backend-software-engineer-go-blr",
        "company_logo": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Swiggy_logo.svg",
        "skills": ["Go", "Redis", "Kafka", "PostgreSQL", "Microservices"],
        "salary_min": 2200000,
        "salary_max": 3000000,
        "currency": "INR",
        "is_seed_data": True,
        "data_origin": "SEED"
    }
]
